version: "3.8"
services:

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/data
  name_server: 
    build: .
    ports:
      - "80:8000"
    depends_on: 
      - redis